/**
*** Author: R-CO
*** Mail: daniel1820kobe@gmail.com
*** Date: 2016-01-08
**/
#ifndef __chess_battle_main_frame__
#define __chess_battle_main_frame__

/**
@file
Subclass of main_frame_base, which is generated by wxFormBuilder.
*/

#include "main_frame_base.h"

//// end generated include

#include <vector>

#include "../chess.h"
#include "../chessboard.h"

/** Implementing main_frame_base */
class ChessBattleMainFrame : public main_frame_base
{
protected:
  // Handlers for main_frame_base events.
  void OnCloseMainFrameBase(wxCloseEvent& event);
  void OnLeftDClickChessBoardPanel(wxMouseEvent& event);
  void OnLeftDownChessBoardPanel(wxMouseEvent& event);
  void OnLeftUpChessBoardPanel(wxMouseEvent& event);
  void OnMotionChessBoardPanel(wxMouseEvent& event);
  void OnPaintChessBoardPanel(wxPaintEvent& event);
  void OnButtonClickNewGame(wxCommandEvent& event);
  void OnRadioBoxPlayModeRadioBox(wxCommandEvent& event);
  void OnTextIpTextCtrl(wxCommandEvent& event);
  void OnTextMaxLenIpTextCtrl(wxCommandEvent& event);
  void OnButtonClickConnectButton(wxCommandEvent& event);
  void OnButtonClickDisconnectButton(wxCommandEvent& event);
  void OnTextChatInputTextCtrl(wxCommandEvent& event);
  void OnTextEnterChatInputTextCtrl(wxCommandEvent& event);

  //
  virtual void Render(wxDC &dc);
  virtual void DrawChessBoard(wxDC &dc);
  virtual void DrawLines(wxDC &dc);
  virtual void DrawText(wxDC &dc);
  virtual void DrawDetail(wxDC &dc, const wxPoint &center, const bool &fixed);

  void InitGui(void);
public:
  /** Constructor */
  ChessBattleMainFrame(wxWindow* parent);
  //// end generated class members

  void PaintNow(void);

protected:
  static const wxBrush        kChessBoardBackgroundBrush_;
  static const wxColour       kChessBoardTextForegroundColour_;
  static const wxString       kLeftChessBoardString_; // wxT("觀棋不語真君子");
  static const wxString       kRightChessBoardString_; //  wxT("觀棋不語真君子");
  static const wxFont         kLeftRightChessBoardTextFont_;

  Chessboard chess_board_;
  std::vector<Chess> chesses_;
};

#endif // __chess_battle_main_frame__
